# dependabot.yml file with updates
# disabled for Docker and limited for npm

version: 2
updates:
    # Configuration for react
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "daily"
        
        
  # Configuration for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
