name: Issue Comments
on:
  issue_comment:
    types: [created, edited]

jobs:
  check_comments:
    name: Check comments for /tag
    runs-on: ubuntu-latest
    steps:
      - name: Check for Command
        id: command
        uses: xt0rted/slash-command-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          command: tag
          reaction: 'true'
          reaction-type: '+1'
          permission-level: write
      - name: Get PR number of merged PR
        uses: 8BitJonny/gh-get-current-pr@2.1.1
        id: PR
      - name: Update PR
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.pulls.update({
              pull_number: ${{ steps.PR.outputs.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'References ['${{ steps.command.outputs.command-arguments }}]'
            })
