name: Issue Comments
on:
  issue_comment:
    types: [created, edited]

jobs:
  check_comments:
    name: Check comments for /tag
    runs-on: ubuntu-latest
    steps:
      - name: Check for Command
        id: command
        uses: xt0rted/slash-command-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          command: tag
          reaction: 'true'
          reaction-type: '+1'
          permission-level: write
      - name: Update PR
        uses: Perdoo/pull-request-update-body-action@v1.0.1
        with:
          ghToken: ${{ secrets.GITHUB_TOKEN }}
          body: |
              References ['${{ steps.command.outputs.command-arguments }}'"]
