name: Issue Comments
on:
  issue_comment:
    types: [created, edited]

jobs:
  check_comments:
    name: Check comments for /tag
    runs-on: ubuntu-latest
    steps:
      - name: Check for Command
        id: command
        uses: xt0rted/slash-command-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          command: tag
          reaction: 'true'
          reaction-type: '+1'
          permission-level: write
      - name: Update PR
        uses: tzkhan/pr-update-action@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          base-branch-regex: 'master'
          body-template: |
            References ['${{ steps.command.outputs.command-arguments }}'"]
          body-update-action: 'suffix'
          body-uppercase-base-match: false
