name: Issue Comments
on:
  issue_comment:
    types: [created, edited]

jobs:
  check_comments:
    name: Check comments for /tag
    runs-on: ubuntu-latest
    steps:
      - name: Check for Command
        id: command
        uses: xt0rted/slash-command-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          command: tag
          reaction: 'true'
          reaction-type: '+1'
          permission-level: write
      - name: Get PR number of merged PR
        uses: 8BitJonny/gh-get-current-pr@2.1.1
        id: PR
        with:
          sha: ${{ github.event.pull_request.head.sha }}
      - name: Update PR
        uses: actions/github-script@v6
        with:
          script: |
            console.log(context.issue.number)
            console.log(context.issue.pull_request)
            console.log(${{ steps.PR.outputs.pr_body }})
            console.log(github.event.pull_request)


