on:
  workflow_dispatch: {}
  pull_request:
    types: [opened, synchronize, reopened]
    
name: pr

jobs: 
  current:
    runs-on: "ubuntu-20.04"
    steps:
      - name: PR
        uses: 8BitJonny/gh-get-current-pr@2.1.1
        id: PR
      - run: echo ${{ steps.PR.outputs.pr_title }}
    outputs:
      pr: ${{ steps.PR.outputs.pr_title }}
  pratchett_pr:
    runs-on: "ubuntu-20.04"
    needs: current
    steps:
      - uses: actions/checkout@v3
        with:
          repository: Gentatsu/lakawordle
          ref: master
          token: ${{ secrets.ACTION_PAT }}
      - run: echo "123" > file.txt
      - run: echo ${{ needs.current.outputs.pr }} 
      - name: Get ticket 
        id: ticket
        run: |
           echo ::set-output name=ticket::$(${{ needs.current.outputs.pr }} | grep -e '[A-Z]\+-[0-9]\+' -o)" 
      - uses: EndBug/add-and-commit@v9
        with:
          message: 'Test'
          add: '*.txt'
          new_branch: ${{ steps.ticket.outputs.ticket }}
      - name: Create Staging PR in Pratchett 
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.pulls.create({
              pull_number: context.issue.number,
              owner: context.repo.owner,
              repo: 'lakawordle',
              head: '${{ steps.ticket.outputs.ticket }}',
              base: 'master',
              title: 'Staging - ${{ steps.ticket.outputs.ticket }}',
              body: ' Ticket ${{ steps.ticket.outputs.ticket }}'
            })
          github-token: ${{ secrets.ACTION_PAT }}
